### PR TITLE
Honour DEPTH_TO configuration value

### PR DESCRIPTION
**Pull request by rkubik**
Credit @antchan2

### CODE REVIEW

**Comment by rkubik** [comment]
The CI error looks unrelated to this change.

**Comment by huntertran** [comment]
this is a more serious problem. I use a clone of `ConfigManager` class in `HeaderManager`, so the custom config was not affected on the generated TOC.

**Comment by rkubik** [comment]
Is a fix for that planned right now?

**Comment by huntertran** [comment]
I already published the fix as beta. Can you check again?

**Comment by rkubik** [comment]
Beta branch changes seem to be working. Thank you.

**Pull request closed without merging**
